### ISSUE TITLE
Если плата уже прошита

### ISSUE THREAD

**Issue by kosyaky** [vooon/elehant-to-mqtt#6]
А если плата уже прошита, можно ли просто добавить счетчик в виде сенсора?

esp32_ble_tracker:

sensor:
  - platform: ble_rssi
    mac_address: AC:37:43:77:5F:4C
    name: "BLE Home"

**Comment by vooon** [comment]
Можно, нужен хедер и вот этот код:

https://github.com/vooon/elehant-to-mqtt/blob/5ba0c3d256d1a562dccfe6f2fb8495093fad1f81/esphome/meter.yaml#L12-L13

https://github.com/vooon/elehant-to-mqtt/blob/5ba0c3d256d1a562dccfe6f2fb8495093fad1f81/esphome/meter.yaml#L143-L170

Но вообще я отказался от варианта на esphome, она больше глючит и теряет пакеты счетчиков.
Уж не знаю, я такой криворукий или стек блютуза у китайцев. Первая прошивка тоже падает, но пропускает меньше данных. Например на графике можно достаточно точно увидеть когда слили воду в унитазе, т.к. период между точками как правило меньше минуты.

**Comment by kosyaky** [comment]
А отказался в пользу чего? Просто у меня ESPhome собирает температуру с
датчиков, там потери не критичны.

вт, 3 нояб. 2020 г., 10:28 Vladimir Ermakov <notifications@github.com>:

**Comment by vooon** [comment]
Так в этом репо в корне лежит проект под PlatformIO.
Эта совершенно отдельная прошивка, с конфигурацией через config.json.
Она слушает БТ и пересылает распарсенное сразу в MQTT. При чем слушает все доступные счетчики.

Конфигурация ESPHome это был эксперимент добавить еще и импульсный вход с электросчетчика, но слишком нестабильно работает.

**Comment by dementeb** [comment]
Добрый день единомышленникам. @vooon спасибо большое! Я использую как раз esphome версию, и в целом в восторге. Железных сенсоров у меня на этой еспхе нет, но мониторю BLE гигрометры сяоми, стоящие неподалёку + монитор присутствия на BLE же. 
Пока подвисаний именно получения данных с элехантов не замечал. Иногда коматозится вся еспха, лечится саморебутом. Так же подвисает другая еспхом32, без элехантов но тоже с BLE мониторингом - почитал и это вроде "фича", при работе wifi+bt на этих платах/проше..

**Comment by kusok18** [comment]
добрый день, помогите оживить счетчики элехант через mqtt
я уже прошивал платы ESP8266 и настраивал их для подключения к брокеру mqtt, но опыта очень мало.
подскажите что надо купить и что надо прошить в плату. Если можно по шагам?
Или я готов купить у вас готовый модуль для двух своих счетчиков, уже прошитый, если можно?
еще вы пишите что эти платы работают не стабильно
есть возможность приобрести у вас готовое решение на PlatformIO?

**Comment by vooon** [comment]
Для этого проекта нужна именно ESP32 (но не ESP32-C3) т.к. у нее есть блютуз. Прошивается она аналогично 8266, так что особых проблем у вас быть не должно.
Весь код открыт, все в этом репо. А также есть предсобанные бинарники PIO, см.: https://github.com/vooon/elehant-to-mqtt/releases/tag/v0.6.1

В целом похоже все кто включает WiFI + BT встречают проблему с зависаниями. Модуль потом самостоятельно перегружается по ватчдогу, так что в целом то оно работает. Просто это не по феншую...

**Comment by vooon** [comment]
Кстати планирую добавить поддержку для платы M5StickC, удобно что это законченное устройство.

А также жду когда приедет ESP32-C3 чтоб попробовать новый RISC-V. Может там будет меньше проблем с Бт.

**Comment by fairslaven** [comment]
Подскажите пожалуйста. Как прошить ESP32, для подключения к ней счетчиков Элехант, через ESPhome вашей прошивкой. Очень хотелось бы что в  НА отображались данные счетчиков.

**Comment by vooon** [comment]
Все делает platformio: `pio run -t upload`

**Comment by fairslaven** [comment]
Я установил platformio и выполнил команду. Что дальше?

**Comment by vooon** [comment]
Плата должна бы запуститься, в терминале будет лог загрузки. Сама плата без конфигурации (или после сброса - GPIO 22 на GND и подать питание), запустит wifi точку доступа `elehant-<mac>`.
Подключаетесь, после чего заходите на http://192.168.4.1 и заливаете config.json в котором настройки вашего wifi и mqtt.

https://github.com/vooon/elehant-to-mqtt/blob/master/example-config.json

**Comment by fairslaven** [comment]
У меня в Home assistant установлен ESPHome в котором, установлена плата ESP32 c прошивкой esp32-bluetooth-prox.
![Снимок](https://github.com/vooon/elehant-to-mqtt/assets/51914082/58d76e90-a085-41d0-a36a-fccabcf9aefa)
Конфигурационный файл прошивки ESP32 выглядит следующим образом.
![Снимок1](https://github.com/vooon/elehant-to-mqtt/assets/51914082/539f6f1b-9b99-4800-b22e-c18669488903)
Что мне сделать и как прошить ESP32 чтобы я мог получать показания со счетчиков? Помогите пожалуйста решить эту задачку.

**Comment by vooon** [comment]
Это отдельная самостоятельная прошивка, esphome ей не нужен.

**Comment by fairslaven** [comment]
А как тогда плата будет передовать показания в home assistant

**Comment by vooon** [comment]
Через MQTT. Плата шлет сообщения на брокер, HA забирает через подобную конфигурацию:
```yaml
mqtt:
  sensor:
  - name: Water1 Total
    state_topic: "tele/water-1/SNS/9953"
    unit_of_measurement: m3
    value_template: '{{ value_json.counter.m3 }}'
    availability_topic: "tele/water-1/LWT"
    payload_available: Online
    payload_not_available: Offline
    icon: mdi:water-pump

  - name: Water1 Meter RSSI
    state_topic: "tele/water-1/SNS/9953"
    unit_of_measurement: dB
    value_template: '{{ value_json.dev.rssi }}'
    availability_topic: "tele/water-1/LWT"
    payload_available: Online
    payload_not_available: Offline
    icon: mdi:signal
```
