### ISSUE TITLE
ESPHome, будь он неладен), не работает

### ISSUE THREAD

**Issue by Rainstation** [vooon/elehant-to-mqtt#7]
Взял чистую ESP 32. Расположил её в метре от счетчика.

Взял части кода с этого проекта, отвечающие непосредственно за съем данных с счетчика воды.

МАК адреса у счетчика:
B0:02:02:00:41:50
B1:02:02:00:41:50

Номер:
16720

Прописал его номер в строке:
meter1->set_serial_no(16720);

Скомпилировал, сканер видит маки счетчика, но никакой информации не извлекает((( в веб пусто, в ха соответственно тоже.

Прошивка компилируется без ошибок, сам код прикладываю. Не пойму, где я сделал не так. Удалил только блоки с вайфай и апи, чтобы не усложнять тут чтение.
```
esphome:
  name: esp32_1
  platform: ESP32
  board: esp-wrover-kit
  includes:
  - /config/esp32_1/elehant_ble.h



esp32_ble_tracker:
  id: ble_tracker
  scan_parameters:
    # interval: 100ms
    # window: 99ms
    duration: 5min
    active: false
    
text_sensor:
  - platform: version
    name: "ESPHome version"

binary_sensor:
  - platform: status
    name: Meter 1 Converter Connected

sensor:
  - platform: uptime
    name: "Meter 1 Uptime"

  - platform: custom
    lambda: |-
      auto meter1 = new ElehantBLE();

      // Set serial number of the device! Like a mac_address for other BLE sensors.
      meter1->set_serial_no(16720);

      // Register
      App.register_component(meter1);
      id(ble_tracker)->register_listener(meter1);
      return {meter1->total_m3_, meter1->total_l_, meter1->rssi_};

    sensors:
      - name: Water1 Total
        unit_of_measurement: m3
        accuracy_decimals: 4
        icon: mdi:water-pump
        id: water1_total_m3
      - name: Water1 Total (liters)
        unit_of_measurement: L
        accuracy_decimals: 1
        icon: mdi:water-pump
        id: water1_total_l
      - name: Water1 Meter RSSI
        unit_of_measurement: dB
        accuracy_decimals: 0
        icon: mdi:signal
        id: water1_rssi

  # - platform: total_daily_energy
  #   name: Water1 Total Liters daily
  #   power_id: water1_total_l

switch:
  - platform: restart
    name: Meter 1 reboot
```
